name: Python CI

on:
  # push:
  pull_request:

jobs:
  lint-test-and-check:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run ruff format
        run: uv run ruff format .

      - name: Run ruff lint
        run: uv run ruff check . --fix

      - name: Run mypy
        run: uv run mypy .

      - name: Run pytest
        run: uv run pytest
