services:
  workspace:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace
    tty: true
    env_file:
      - ../.env
    environment:
      - PYTHONPATH=/workspace/src
    shm_size: 8gb
